version: '2'

services:
  app:
    build: .
    entrypoint: ./docker-entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    network_mode: host

networks:
  outside:
    external: true
